/**
 * DynamicCSSManager
 * 
 * Manages dynamic CSS injection for hiding space folders from Obsidian UI.
 * Uses DOM <style> element instead of CSS snippet files for automatic cleanup.
 */

export class DynamicCSSManager {
  private styleElement: HTMLStyleElement | null = null;
  private currentPattern: string | null = null;

  /**
   * Apply CSS hiding for the given pattern
   * @param pattern - Folder name to hide (e.g., "_space", ".space")
   */
  public apply(pattern: string): void {
    // Remove existing style if any
    this.remove();

    // Create new style element
    this.styleElement = document.createElement('style');
    this.styleElement.id = 'makemd-dynamic-space-hiding';
    this.styleElement.setAttribute('data-makemd-managed', 'true');
    this.styleElement.textContent = this.buildCSS(pattern);

    // Inject into DOM
    document.head.appendChild(this.styleElement);

    this.currentPattern = pattern;
  }

  /**
   * Remove CSS hiding
   */
  public remove(): void {
    if (this.styleElement) {
      this.styleElement.remove();
      this.styleElement = null;
    }
    this.currentPattern = null;
  }

  /**
   * Check if hiding is currently active
   */
  public isActive(): boolean {
    return this.styleElement !== null && document.head.contains(this.styleElement);
  }

  /**
   * Get current pattern
   */
  public getCurrentPattern(): string | null {
    return this.currentPattern;
  }

  /**
   * Rebuild CSS with new pattern
   * @param pattern - New folder name to hide
   */
  public rebuild(pattern: string): void {
    this.apply(pattern);
  }

  /**
   * Build CSS rules for hiding the pattern
   * @param pattern - Folder name to hide
   */
  private buildCSS(pattern: string): string {
    const escapedPattern = this.escapeForCSS(pattern);

    return [
      '/* Auto-generated by Make.md - Dynamic Space Folder Hiding */',
      '/* DO NOT EDIT - This style is managed automatically */',
      '',
      '/* File Explorer */',
      `.nav-folder-title[data-path*="${escapedPattern}"],`,
      `.tree-item[data-path*="${escapedPattern}"],`,
      `.tree-item-self[data-path*="${escapedPattern}"] {`,
      '  display: none !important;',
      '}',
      '',
      '/* Search Results */',
      `.search-result-file-title[data-path*="${escapedPattern}"],`,
      `.search-result-container[data-path*="${escapedPattern}"] {`,
      '  display: none !important;',
      '}',
      '',
      '/* Quick Switcher */',
      `.suggestion-item[data-path*="${escapedPattern}"],`,
      `.suggestion-content[data-path*="${escapedPattern}"] {`,
      '  display: none !important;',
      '}',
      '',
      '/* Link lists and backlinks */',
      `.tree-item-inner[data-path*="${escapedPattern}"] {`,
      '  display: none !important;',
      '}',
      '',
      '/* Files inside space folder */',
      `.nav-file-title[data-path*="${escapedPattern}/"] {`,
      '  display: none !important;',
      '}',
      '',
      '/* Note: Graph View requires manual configuration */',
      '/* See documentation for Graph View setup */',
    ].join('\n');
  }

  /**
   * Escape special characters for CSS attribute selector
   * @param pattern - Pattern to escape
   */
  private escapeForCSS(pattern: string): string {
    // Escape special CSS characters
    // For attribute selectors, we need to escape: " \ 
    return pattern.replace(/["\\]/g, '\\$&');
  }
}
